import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
    js.configs.recommended,
    ...tseslint.configs.recommended,
    {
        ignores: [
            // Generated by bddgen from .feature files — regenerated on every
            // pretest run, never hand-edited.
            ".features-gen/**",
        ],
    },
    {
        files: ["**/*.ts"],
        rules: {
            "@typescript-eslint/no-empty-object-pattern": "off",
            "no-empty-pattern": "off",
            // Playwright lifecycle signatures receive config objects they
            // legitimately ignore: keep the `_` convention expressible.
            "@typescript-eslint/no-unused-vars": [
                "error",
                { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
            ],
        },
    },
    {
        // Node scripts (CI matrix guard): plain node globals without
        // pulling the `globals` package in.
        files: ["scripts/**/*.mjs"],
        languageOptions: {
            globals: {
                console: "readonly",
                process: "readonly",
                URL: "readonly",
            },
        },
    },
);
