# ruff: noqa: E501
"""One-shot manual EN translation table for cdn/dictionary/radicals.json.

REGENERATED from the shipped radicals.json after the canonical correction
passes (see radicals_canonical_fixes.py + apply_radicals_fixes.py): the
table mirrors the file exactly, so re-running apply_radicals_en.py on a
fresh clone reproduces the corrected state directly.

Each tuple: (radical char, name_en, description_en).
"""

TRANSLATIONS = [
    ('一', 'One', "The radical means 'one' and appears in kanji related to unity, simplicity, or a horizontal position."),
    ('｜', 'Line', 'A basic radical depicting a vertical line, often used in kanji related to height, top-to-bottom direction, or stability.'),
    ('丶', 'Dot', 'Denotes a small stroke above the main part of the kanji and serves as an auxiliary element that changes the meaning or reading.'),
    ('ノ', 'Slash', 'A slanted stroke, the graphical form of the 丿 radical; used as a shape element in the top and left parts of kanji.'),
    ('乙', 'Second', "Indicates the concept of 'second', 'next', or 'changeable', often used in words related to repetition or a change of states."),
    ('亅', 'Hook', 'A vertical stroke ending in a hook; a shape element at the bottom of kanji.'),
    ('二', 'Two', "The radical means the number 'two' and is used in words related to pairing, division, or second place."),
    ('亠', 'Lid', 'Depicts a lid or a cover on top; appears in the upper part of kanji (京, 交).'),
    ('人', 'Person', 'A radical depicting a person, often used in kanji related to people, social concepts, or actions.'),
    ('化', 'Change', 'Indicates change, transformation, or chemical processes.'),
    ('个', 'Person', 'A radical meaning a person or individuality, often used in kanji related to people and their attributes.'),
    ('儿', 'Legs', "Depicts a person's legs; appears at the bottom of kanji related to people and their stance (兄, 元, 光)."),
    ('入', 'Enter', 'Indicates meanings related to entering, penetrating into something, or being included in a composition.'),
    ('ハ', 'Divide', "A graphical variant of 八 'eight'; depicts a split into two parts."),
    ('并', 'Parallel', 'Denotes parallelism, adjacency, or joint action.'),
    ('冂', 'Border box', 'A box open at the bottom; denotes a border or an enclosure (同, 円).'),
    ('冖', 'Roof', 'A radical depicting a roof or an upper part, often used in kanji related to buildings, shelter, or protection.'),
    ('冫', 'Ice', 'A radical denoting ice or cold; used in kanji related to freezing, winter, and low temperatures.'),
    ('几', 'Table', 'A radical depicting a table or stand, often used in kanji related to writing, drafting, or objects on a surface.'),
    ('凵', 'Receptacle', 'Depicts a container open at the top; used when something is placed inside (凶, 函).'),
    ('刀', 'Knife', 'Denotes weapons, cutting tools, or actions related to cutting.'),
    ('刈', 'Knife', 'A radical meaning a knife or cutting tool, often used in kanji related to the act of cutting.'),
    ('力', 'Power', 'Denotes strength, might, or effort and is often used in words related to physical strength, energy, or power.'),
    ('勹', 'Wrap', 'Depicts a wrapping arm; the enveloping component in kanji like 包, 句.'),
    ('匕', 'Spoon', 'Depicts a spoon; appears in kanji of comparison and direction (比, 北).'),
    ('匚', 'Box', 'Depicts a box open on the right; relates to containers and their contents (医, 匠, 匹).'),
    ('十', 'Ten', 'A radical meaning the number ten, often used in kanji related to numerals, order, or measurement.'),
    ('卜', 'Divination', 'Indicates fortune-telling, prophecy, and the related rituals or practices.'),
    ('卩', 'Seal', 'Depicts a seal or a seated figure; a component in kanji related to seals and status (印, 卵).'),
    ('厂', 'Cliff', 'Depicts an overhanging cliff or slope; appears in kanji related to rocks and terrain (原, 厚).'),
    ('厶', 'Hidden', 'Indicates meanings related to covering, often used in words meaning clothing or headwear.'),
    ('又', 'Hand', 'Indicates a connection with the hand, action, or repetition within kanji.'),
    ('マ', 'Ma shape', 'A graphical component shaped like katakana マ (an angled stroke); the top part of kanji like 柔, 矛, 勇, 通.'),
    ('九', 'Nine', 'A radical meaning the number nine, often used in kanji related to numeric values or certain concepts.'),
    ('ユ', 'Yu shape', 'A graphical component shaped like katakana ユ; the top part of kanji like 為, 快, 決.'),
    ('乃', 'Namely', "A classical word meaning 'namely, thereupon'; a component in kanji like 孕, 仍, 秀."),
    ('乞', 'Request', 'Indicates the meaning of request, appeal, or dependence in kanji.'),
    ('込', 'Enter', 'Denotes entering, immersion inside, or putting something in.'),
    ('口', 'Mouth', "The 'Mouth' radical means a mouth or an opening and is often used in words related to speech, food, or cavities."),
    ('囗', 'Enclosure', 'Depicts a fence or an enclosed space; enclosure and bounds (国, 団, 困).'),
    ('土', 'Earth', 'Denotes earth, soil, or ground; often found in words related to land, construction, and basic concepts.'),
    ('士', 'Warrior', 'Denotes a warrior, soldier, or military concepts and is often used in kanji related to military topics.'),
    ('夂', 'Slow step', "Depicts a walking figure or a footprint; means 'to go slowly, to follow'; the radical's Japanese name is ふゆがしら ('winter head')."),
    ('夕', 'Evening', 'A radical meaning evening or sunset, often used in kanji related to times of day or the completion of something.'),
    ('大', 'Big', "A radical meaning 'big' or 'great', often used in words related to scale, importance, or size."),
    ('女', 'Woman', 'Indicates a connection with women, motherhood, or feminine concepts in words.'),
    ('子', 'Child', 'Denotes a child, offspring, or a young individual and is often used as a prefix in words related to childhood or youth.'),
    ('宀', 'House roof', 'Refers to meanings related to home, family, or dwelling.'),
    ('寸', 'Finger', 'A radical depicting a finger or an inch, often used in kanji related to measurement, small objects, or hand-performed actions.'),
    ('小', 'Small', 'Indicates something small, minor, or childlike, often used in words related to children or small objects.'),
    ('尚', 'Esteem', "Means 'still, to esteem'; the top part of kanji like 常, 堂, 裳."),
    ('尢', 'Lame', 'Depicts a bent figure; relates to crookedness, lameness, and deviation.'),
    ('尸', 'Corpse', 'Refers to meanings related to death, burial, or inaction.'),
    ('屮', 'Sprout', 'Depicts a sprouting grass shoot; a graphical variant of 艸.'),
    ('山', 'Mountain', 'This radical means a mountain and is used in kanji related to elevations, natural objects, or geographic names.'),
    ('川', 'River', 'Indicates a river, water, or flow within kanji.'),
    ('巛', 'Winding river', 'A graphical variant of 川; depicts a winding stream of water.'),
    ('工', 'Work', 'Depicts a person working with their hands and is often used in words related to labor, construction, or craft.'),
    ('已', 'Already', "Means 'already'; one of the three similar characters 己, 已, 巳."),
    ('巾', 'Towel', 'Indicates a connection with cloth, clothing, or textiles within kanji.'),
    ('干', 'Dry', "Means 'dry'; historically depicted a shield; a component in kanji like 刊, 幹, 汗."),
    ('幺', 'Thread', 'Indicates meanings related to threads, fabrics, or flexible objects.'),
    ('广', 'Building', 'A radical denoting a building or premises, often used in words related to houses, shops, theaters, and other structures.'),
    ('廴', 'Stride', 'Depicts a long step forward; relates to movement and progress (建, 延).'),
    ('廾', 'Two hands', 'Depicts two raised hands; graphically identical to the number twenty; a component of two-handed actions (開, 弄).'),
    ('弋', 'Hunt', 'A radical meaning hunting or archery, often used in words related to hunting activities or bows.'),
    ('弓', 'Bow', 'A radical depicting a bow; used in kanji related to archery, weapons, and swift actions.'),
    ('ヨ', 'Yo shape', 'A graphical variant of 彐 shaped like katakana ヨ; appears in kanji like 君, 帰, 兼.'),
    ('彑', 'Snout (variant)', "A rare variant of the 彐 radical 'snout'; the top part of kanji like 互, 彙."),
    ('彡', 'Pattern', 'Three strokes depicting hair, feathers, or a decorative pattern; conveys ornamentation (形, 彩).'),
    ('彳', 'Going man', 'Depicts a walking person; the left half of 行; relates to movement and roads (往, 徒, 待).'),
    ('忙', 'Busyness', 'Denotes a state of being busy or a lack of free time, often used in words related to work and affairs.'),
    ('扎', 'Needle', 'Denotes a piercing tool or the act of piercing, often used in words related to needles or pricks.'),
    ('汁', 'Juice', 'Denotes liquid, juice, or moisture and is used in kanji related to fluids or liquids.'),
    ('犯', 'Crime', 'Refers to meanings related to crimes, violations of the law, or guilt.'),
    ('艾', 'Herb', 'Indicates a connection with herbs, plants, or medicine in kanji.'),
    ('邦', 'Country', 'Refers to concepts related to a country, state, or nation.'),
    ('阡', 'Footpath', 'A footpath or a boundary between rice fields; relates to field paths and borders.'),
    ('也', 'Also', "Indicates similarity, addition, or connection; often means 'also' or 'and'."),
    ('亡', 'Perish', "Means 'to perish, to disappear, to lose'; relates to loss and disappearance (亡くす, 忙, 忘)."),
    ('及', 'Reaching', 'Indicates reaching, extending, or a connection with something.'),
    ('久', 'Duration', 'Indicates duration, length, or a long time.'),
    ('老', 'Old', 'A radical meaning old age or an elderly person, often used in kanji related to age, wisdom, or maturity.'),
    ('心', 'Heart', "Refers to emotions, feelings, and thoughts; often found in words related to a person's inner state."),
    ('戈', 'Spear', 'Refers to meanings related to war, combat, or weapons.'),
    ('戸', 'Door', 'A radical meaning a door or entrance, used in kanji related to doors, houses, and boundaries.'),
    ('手', 'Hand', 'Denotes a hand or hand action, often used in kanji related to manipulation, labor, and contact.'),
    ('支', 'Branch', 'Denotes a tree branch or support; often used in words related to subdivisions, branches, and auxiliary elements.'),
    ('攵', 'Tap', "Depicts a hand holding a stick, striking; means 'to tap, to strike'; the Japanese radical name is ぼくづくり (教, 数, 敗)."),
    ('文', 'Writing', 'A radical meaning writing or literature, used in kanji related to text, documents, and education.'),
    ('斗', 'Bucket', 'Refers to the meaning of a volume measure or a vessel within kanji.'),
    ('斤', 'Axe', 'A radical depicting an axe or hammer, used in kanji related to chopping, striking, or splitting.'),
    ('方', 'Direction', 'Denotes direction, side, or square and is often used in kanji related to spatial orientation, angles, and geometric shapes.'),
    ('无', 'Nothing', "A variant of 無; means 'nothing, not have', the negation of existence."),
    ('日', 'Sun', "The 'Sun' radical means daylight and day and is often used in kanji related to time, warmth, and solar energy."),
    ('曰', 'Say', "Depicts a word coming out of a mouth; means 'to say, to utter'."),
    ('月', 'Moon', 'Denotes the moon or a month and is used in words related to time, the calendar, or lunar cycles.'),
    ('木', 'Tree', 'A radical denoting a tree, plant, or wooden objects, often used in kanji related to nature and wooden items.'),
    ('欠', 'Lack', 'This radical means absence, shortage, or defect and is used in kanji related to such concepts.'),
    ('止', 'Stop', "Depicts a foot planted on the ground; means 'to stop' (止まる); a component of halting and stillness (歩, 此)."),
    ('歹', 'Death', 'Depicts a bare bone; relates to death, demise, and the bad (死, 残, 危).'),
    ('殳', 'Spear', 'Refers to meanings related to weapons, violence, or combat operations.'),
    ('比', 'Comparison', 'Indicates comparison, analogy, or equality, often used in words related to matching objects.'),
    ('毛', 'Hair', 'A radical meaning hair or fur, used in kanji related to fibrous materials or furry animals.'),
    ('氏', 'Family', 'A radical meaning family or clan, often used in Japanese surnames and words related to kinship.'),
    ('气', 'Air', 'Refers to concepts related to air, breath, wind, or emotional state.'),
    ('水', 'Water', 'A radical denoting water, used in kanji related to aquatic elements, liquids, or rain.'),
    ('火', 'Fire', 'Refers to meanings related to fire, flame, or heat, and can also denote brightness or speed.'),
    ('杰', 'Outstanding person', 'Denotes an outstanding, talented, or heroic person and is used in kanji related to exceptional individuals or abilities.'),
    ('爪', 'Claw', 'A radical depicting a claw or paw, often used in kanji related to hands, feet, and animals.'),
    ('父', 'Father', 'A radical denoting a father or parenthood, used in words related to family relationships and origin.'),
    ('爻', 'Hexagram lines', 'Crossing lines of the I Ching hexagrams; a symbol of divination and change (卦).'),
    ('爿', 'Split wood', 'The mirror form of 木; depicts a split log, the left half of a tree (状, 壮).'),
    ('片', 'Half', 'The right half of a tree, the counterpart of 爿; denotes a part, a half, a fragment (版, 牌).'),
    ('牛', 'Cow', 'A radical depicting a cow, often used in kanji related to cattle, farming, and animal husbandry products.'),
    ('犬', 'Dog', "The 'Dog' radical is used in kanji related to dogs and animals, and can also denote aggressiveness or speed."),
    ('礼', 'Courtesy', 'Refers to concepts related to politeness, bows, and etiquette in Japanese kanji.'),
    ('王', 'King', 'Denotes a king or monarch and is used in kanji related to power, rule, or titles.'),
    ('元', 'Origin', "Denotes a beginning, basis, or primary state, often used in the meanings 'first', 'main', or 'original'."),
    ('井', 'Well', 'A radical depicting a well or water source, often used in kanji related to water, resources, or distribution.'),
    ('勿', 'Prohibition', 'A radical denoting negation, prohibition, or warning.'),
    ('尤', 'Special', 'Indicates something special, exceptional, or the best.'),
    ('五', 'Five', 'Denotes the number five and is used as a radical in kanji related to concepts of fiveness or the figure five.'),
    ('屯', 'Fortress', 'Refers to meanings related to camps, fortifications, or settled posts.'),
    ('巴', 'Tomoe', 'A curved comma-shaped element (tomoe); originally a serpent or a claw; a component in kanji like 把, 色, 肥.'),
    ('毋', 'Negation', 'Indicates negation, absence, or prohibition in a word.'),
    ('玄', 'Mystery', 'Denotes mystery, depth, or something hidden, often used in words related to secret knowledge, depth of thought, or mysticism.'),
    ('瓦', 'Tile', 'Indicates a connection with tiles, brick, or building materials in the words where it is used.'),
    ('甘', 'Sweet', 'A radical meaning sweetness, used in kanji related to a sweet taste or sensory pleasures.'),
    ('生', 'Life', 'Denotes life, birth, and growth, and is used in words related to living beings, nature, and biology.'),
    ('用', 'Use', 'Denotes the use, application, or purpose of something.'),
    ('田', 'Field', 'A radical meaning a field or farmland, often used in words related to farming and agriculture.'),
    ('疋', 'Bolt of cloth', 'Depicts rolled cloth; a cloth measure (a bolt); graphically often doubles for 足 (楚, 疎).'),
    ('疔', 'Ulcer', 'Refers to a meaning related to skin diseases, ulcers, or growths.'),
    ('癶', 'Footsteps apart', 'Two feet pointing in opposite directions; movement and alternating steps (登, 発).'),
    ('白', 'White', "The 'White' radical means the color white, purity, or light and is used in kanji related to these concepts."),
    ('皮', 'Skin', 'Indicates a connection with skin, hide, or feathers, and can also denote removal or taking off.'),
    ('皿', 'Plate', 'Refers to dishes, plates, or flat objects and is used in kanji related to food and the kitchen.'),
    ('目', 'Eye', "A radical meaning 'eye' or 'sight', often used in kanji related to seeing, observation, and visual perception."),
    ('矛', 'Spear', 'A radical meaning a spear or an elongated sharp object, often used in kanji related to weapons and combat.'),
    ('矢', 'Arrow', 'Refers to meanings related to arrows, throwing, direction, or swift movement.'),
    ('石', 'Stone', 'Indicates a connection with stone, rock, or earth in compound kanji.'),
    ('示', 'Show', 'Denotes showing, demonstration, or religious rituals, often used in kanji related to indication and spiritual practice.'),
    ('禹', 'Emperor Yu', 'The name of the legendary Emperor Yu who tamed the flood; a component in kanji like 属, 遇, 愚.'),
    ('禾', 'Grain ear', 'A radical depicting ears of grain, used in words related to agriculture, harvest, and cereal crops.'),
    ('穴', 'Hole', 'A radical meaning a hole, opening, or burrow, used in words related to cavities, voids, and underground spaces.'),
    ('立', 'Stand', "Depicts a person standing on the ground; means 'to stand' (位)."),
    ('初', 'First', 'Indicates a beginning, a first time, or novelty; often used in words related to a first action, an initial stage, or a first experience.'),
    ('世', 'World', 'Denotes the world, the universe, or a generation; often used in words related to public life, time, and generations.'),
    ('巨', 'Giant', 'Denotes something enormous, gigantic, or important and is often used in words related to large size or significance.'),
    ('冊', 'Book', 'A radical denoting a book or scroll, used in kanji related to writing, documents, and printed materials.'),
    ('母', 'Mother', "A radical meaning 'mother' or 'woman', used in kanji related to the feminine principle and family relationships."),
    ('買', 'Purchase', 'A radical denoting buying or trade, used in words related to purchasing goods or services.'),
    ('牙', 'Fang', 'A radical meaning a fang or tooth, used in kanji related to animals, teeth, or sharp objects.'),
    ('瓜', 'Melon', "A radical meaning 'melon' or 'cucumber', used in kanji related to vegetables and plant fruits."),
    ('竹', 'Bamboo', 'Indicates bamboo and is used in kanji related to plants, tools, and objects shaped like bamboo.'),
    ('米', 'Rice', "A radical meaning 'rice' or 'grain', often used in words related to rice, cereals, and food."),
    ('糸', 'Thread', 'Indicates thread, silk, or textile-related concepts in compound kanji.'),
    ('缶', 'Can', 'A radical meaning a metal container or vessel, used in kanji related to metal and tableware.'),
    ('羊', 'Sheep', 'Points to a sheep, a goat, or related concepts such as wool and pasture.'),
    ('羽', 'Feather', 'Refers to meanings related to birds, flight, or feathers.'),
    ('而', 'Contrast', "Indicates contrast or addition in a sentence, often translated as 'and', 'but', or 'however'."),
    ('耒', 'Hoe', 'A radical depicting a hoe, used in kanji related to farming and rural life.'),
    ('耳', 'Ear', "This radical means 'ear' and is used in kanji related to hearing, sound perception, or the sense organs."),
    ('聿', 'Writing', 'A radical depicting a quill or writing instrument, used in kanji related to writing and calligraphy.'),
    ('肉', 'Meat', 'A radical meaning meat or flesh, used in kanji related to living beings and physical flesh.'),
    ('自', 'Self', 'Denotes selfhood, personal actions, or belonging to a person.'),
    ('至', 'Arrival', 'A radical meaning arrival, completion, or direction up to a certain point.'),
    ('臼', 'Mortar', 'A radical depicting a mortar, used in kanji related to grinding, crushing, or actions performed with a mortar.'),
    ('舌', 'Tongue', 'A radical depicting the tongue or speech, used in kanji related to voice, pronunciation, and communication.'),
    ('舟', 'Boat', 'A radical meaning a boat or ship, used in words related to water transport and navigation.'),
    ('艮', 'Stopping', "Means 'blunt, coming to a stop'; the 'mountain' trigram of the I Ching; a component in kanji like 良, 限, 根."),
    ('色', 'Color', 'Indicates a connection with colors, tinting, or visual perception in compound kanji.'),
    ('虍', 'Tiger', "Depicts a tiger's hide; the top part of 虎 and its kin (虚, 慮)."),
    ('虫', 'Insect', "The radical means 'insect' or 'worm' and is used in kanji related to small living creatures."),
    ('血', 'Blood', 'Refers to meanings related to blood, the human body, and biological processes.'),
    ('行', 'Movement', 'Refers to movement, travel, or transport in words related to journeys and actions.'),
    ('衣', 'Clothing', 'A radical denoting clothing, fabrics, or actions related to wearing clothes.'),
    ('西', 'West', 'Denotes the western direction or Western countries; often used in words related to the West or western regions.'),
    ('臣', 'Servant', 'Represents a servant, subject, or vassal and is used in kanji related to service, subordination, and civil service.'),
    ('見', 'Look', 'Refers to meanings related to sight, observation, or inspection.'),
    ('角', 'Angle', 'Denotes concepts related to an angle, an edge, or horns, and is often used in words meaning body parts, geometric terms, or horned animals.'),
    ('言', 'Speech', 'Denotes speech, words, or utterance and is used in kanji related to communication, language, and expressing thoughts.'),
    ('谷', 'Valley', "The 'Valley' radical means depressions, valleys, or unevenness and is often used in words related to terrain or spatial concepts."),
    ('豆', 'Bean', 'Denotes leguminous plants, beans, and related products or concepts.'),
    ('豕', 'Pig', 'A radical depicting a pig, used in kanji related to animals or certain concepts.'),
    ('豸', 'Badger', 'Depicts a badger, a small predatory animal; relates to beasts and their traits (豹, 貌).'),
    ('貝', 'Shell', 'Indicates a connection with mollusks, shells, or shell structures in kanji.'),
    ('赤', 'Red', "The radical means 'red' and is used in kanji related to the color red, fire, passion, or aggression."),
    ('走', 'Run', 'This radical means movement or running and is used in kanji related to action and motion.'),
    ('足', 'Leg', 'Refers to meanings related to the leg, movement, position, or the ability to move.'),
    ('身', 'Body', 'A radical depicting the human body and meaning a person, a living being, or a physical form.'),
    ('車', 'Vehicle', 'A radical denoting vehicles such as cars, trains, and other kinds of machinery.'),
    ('辛', 'Bitter', "The radical means 'bitter' or 'difficult' and is often used in words related to hardship, effort, or intensity (for example, 辛い 'bitter' and 辛労 'hard toil')."),
    ('辰', 'Zodiac dragon', "Means 'morning, celestial body'; the fifth zodiac sign — the dragon; a component in kanji like 農, 振."),
    ('酉', 'Sake vessel', "Depicts a clay sake jar; its Japanese radical name is とり ('bird', the zodiac rooster); marks alcohol kanji (酒, 酔)."),
    ('釆', 'Grain', 'Depicts scattered grains; conveys the meaning of distinguishing (番, 悉, 釈).'),
    ('里', 'Village', 'Denotes rural areas, a village, or a place of residence.'),
    ('舛', 'Discord', 'Feet turned in opposite directions; the meanings of discord and error (舞).'),
    ('麦', 'Cereals', 'Denotes cereal crops and is used in kanji related to grain and agriculture.'),
    ('金', 'Metal', 'Denotes metal, gold, or money and is used in kanji related to metallic materials, wealth, and trade.'),
    ('長', 'Length', 'Denotes length or duration and is used in kanji related to duration.'),
    ('門', 'Gate', 'Refers to kanji related to entrances, doors, access, or boundaries.'),
    ('隶', 'Subjugate', 'Depicts a hand grabbing prey by the tail; the meanings of subduing and servitude (逮, 隷, 康).'),
    ('隹', 'Bird', 'A radical meaning a bird, used in kanji related to feathered creatures and flight.'),
    ('雨', 'Rain', 'A radical meaning rain, used in kanji related to weather, water, or atmospheric phenomena.'),
    ('青', 'Blue', 'A radical meaning the color blue or green, often used in words related to youth, inexperience, or nature.'),
    ('非', 'Falsehood', 'Indicates negation, falsity, or erroneousness within kanji.'),
    ('奄', 'Cover', "Means 'to cover, suddenly'; a component in kanji like 掩, 俺, 庵."),
    ('岡', 'Hill', 'This radical means a hill or mountain and is used in kanji related to elevations, land, or the countryside.'),
    ('免', 'Exemption', 'Indicates exemption or release from something (for example, from obligations, taxes, or punishment).'),
    ('斉', 'Equal', 'Denotes the meanings of equality, symmetry, or harmony in the kanji associated with it.'),
    ('面', 'Face', 'Denotes a face, surface, or side and is used in kanji related to appearance, expression, or treatment.'),
    ('革', 'Leather', 'A radical meaning hide or change, often used in words related to leather, footwear, and transformations.'),
    ('韭', 'Leek', 'A radical denoting greens or leek, used in kanji related to vegetables and plants.'),
    ('音', 'Sound', 'A radical denoting sound, voice, or music, used in kanji related to hearing and acoustic phenomena.'),
    ('頁', 'Head', 'A radical meaning a human head or a book page, often used in kanji related to thinking, knowledge, or sheets of text.'),
    ('風', 'Wind', 'Refers to meanings related to wind, air, movement, or change, and often appears in words describing atmospheric phenomena, behavior, or direction.'),
    ('飛', 'Fly', "Depicts a bird in flight; means 'to fly'; flight and swiftness."),
    ('食', 'Food', 'A radical denoting food, eating, or consumption, used in kanji related to cooking and food intake.'),
    ('首', 'Head', 'A radical depicting the head or neck, used in words related to the head, leadership, or first place.'),
    ('香', 'Scent', 'This radical means smell or fragrance and is used in kanji related to incense, flowers, and other aromatic substances.'),
    ('品', 'Goods', "The 'Goods' radical is used in kanji related to products, goods, quality, and grade (for example, in the words 品質 'quality' and 品種 'variety')."),
    ('馬', 'Horse', "This radical means 'horse' and is used in kanji related to horses, horseback riding, and horse breeding."),
    ('骨', 'Bone', 'Refers to meanings related to bones, the skeleton, or a hard structure in kanji.'),
    ('高', 'Height', 'Denotes height, elevation, or exaggeration, often used in words related to a high level or quality.'),
    ('髟', 'Hair', 'Indicates a connection with hair or the head within kanji.'),
    ('鬥', 'Fight', 'Refers to conflict, quarrel, or physical confrontation.'),
    ('鬯', 'Sake', 'Refers to meanings related to alcohol, brewing, or intoxicating substances.'),
    ('鬲', 'Cauldron', 'A radical meaning a cauldron or pot, used in kanji related to boiling and cookware.'),
    ('鬼', 'Demon', 'Refers to demons, ghosts, or malevolent beings and often appears in words related to evil or the supernatural.'),
    ('竜', 'Dragon', 'A radical depicting a dragon, used in kanji related to dragons, power, or movement.'),
    ('韋', 'Tanned leather', "Means 'tanned leather'; in old kanji — leatherwork and defense (衛)."),
    ('魚', 'Fish', 'A radical denoting fish or sea creatures, used in words related to aquatic fauna.'),
    ('鳥', 'Bird', 'A radical used to denote birds or feathers in kanji.'),
    ('鹵', 'Salt', 'Denotes kanji related to salty substances, chemical processes, or seasoning.'),
    ('鹿', 'Deer', 'A radical depicting a deer, used in words related to deer or certain concepts in the Japanese language.'),
    ('麻', 'Hemp', 'A radical meaning hemp or flax, used in kanji related to plant fibers, textiles, and medicine.'),
    ('亀', 'Turtle', 'A radical meaning a turtle, used in kanji related to longevity, wisdom, and stability.'),
    ('滴', 'Drop', 'Indicates a connection with water, drops, or fluidity in kanji.'),
    ('黄', 'Yellow', 'Indicates the color yellow and is used in kanji related to the yellow color, the sun, or ripeness.'),
    ('黒', 'Black', 'Refers to meanings related to the color black, darkness, or negative concepts.'),
    ('黍', 'Millet', 'A radical denoting millet or cereal crops, used in kanji related to plants and agriculture.'),
    ('黹', 'Embroidery', 'Depicts embroidery or stitches; relates to sewing and needlework.'),
    ('無', 'Nothing', 'Indicates absence, nothing, or negation; often used in words expressing the absence of something or a negative meaning.'),
    ('歯', 'Tooth', "A radical meaning 'tooth', used in kanji related to teeth, dentistry, and dental care."),
    ('黽', 'Frog', 'This is a radical depicting a frog and used in kanji related to amphibians or certain natural phenomena.'),
    ('鼎', 'Cauldron', "The radical means 'cauldron' and is used in kanji related to cooking food or metal vessels."),
    ('鼓', 'Drum', 'Refers to concepts related to music, signals, or a call to action.'),
    ('鼠', 'Rat', "The radical means 'rat' or 'mouse' and is used in kanji related to rodents, nocturnal creatures, or darkness."),
    ('鼻', 'Nose', "A radical meaning 'nose', used in kanji related to smell or the face."),
    ('齊', 'Equal (traditional)', "The traditional form of 斉; means 'equal, neat, to align'."),
]
