use crate::repository::{
    cdn_provider, delete_cached_lindera, get_cached_lindera_rkyv, save_lindera_to_cache_rkyv,
};
use crate::utils::{now_ms, yield_to_browser};
use origa::domain::{OrigaError, init_tokenizer_from_rkyv_cached, is_dictionary_loaded};
use origa::traits::CdnProvider;

/// CDN path to the pre-built rkyv lindera dictionary blob.
///
/// Generated by `cargo run --bin build-lindera-cache` from the raw
/// lindera files. The blob contains serialised `CachedLinderaDictionary`
/// structures (ConnectionCostMatrix, PrefixDictionary, etc.) and is
/// downloaded directly — no build/serialize happens on-device.
const LINDERA_BLOB_CDN_PATH: &str = "dictionaries/cached-lindera.bin";

/// Load the Unidic dictionary.
///
/// Unified path for cache-hit and cache-miss: download/restore a single
/// pre-built rkyv blob → `from_bytes` → init. Peak WASM heap is bounded by
/// rkyv bytes + lindera structures coexisting during `from_bytes`.
pub async fn load_dictionary() -> Result<(), OrigaError> {
    if is_dictionary_loaded() {
        tracing::debug!("📖 Dictionary already loaded");
        return Ok(());
    }
    let start = now_ms();
    tracing::info!("📖 Loading Unidic dictionary...");

    // Try Cache API first.
    match get_cached_lindera_rkyv().await {
        Ok(Some(bytes)) => {
            tracing::info!("📖 Cached lindera blob found, {} bytes", bytes.len());
            yield_to_browser().await;
            match init_tokenizer_from_rkyv_cached(&bytes) {
                Ok(()) => {
                    tracing::info!(
                        "📖 Dictionary loaded from cache ({:.2}s)",
                        (now_ms() - start) / 1000.0
                    );
                    return Ok(());
                },
                Err(e) => {
                    tracing::warn!(
                        error = ?e,
                        "Corrupted lindera cache, deleting and falling back to CDN"
                    );
                    if let Err(del_err) = delete_cached_lindera().await {
                        tracing::warn!("Failed to delete corrupted cache: {:?}", del_err);
                    }
                },
            }
        },
        Ok(None) => {
            tracing::debug!("📖 No cached lindera blob, downloading from CDN");
        },
        Err(e) => {
            tracing::warn!("Cache read failed, downloading from CDN: {:?}", e);
        },
    }

    // Cache-miss: download the pre-built rkyv blob from CDN.
    let cdn = cdn_provider();
    let bytes = cdn.fetch_bytes(LINDERA_BLOB_CDN_PATH).await?;
    tracing::info!(
        "📖 Downloaded lindera blob ({} bytes, {:.2}s)",
        bytes.len(),
        (now_ms() - start) / 1000.0
    );

    // Save to Cache API for future loads (best-effort, non-blocking UX).
    if let Err(e) = save_lindera_to_cache_rkyv(&bytes).await {
        tracing::warn!("Failed to cache lindera blob: {:?}", e);
    }

    yield_to_browser().await;
    init_tokenizer_from_rkyv_cached(&bytes)?;

    tracing::info!(
        "📖 Dictionary loaded from CDN ({:.2}s)",
        (now_ms() - start) / 1000.0
    );
    Ok(())
}
